### PR TITLE
Fix -spec's to compile in Erlang/OTP 19

### PR DESCRIPTION
**Pull request by leoliu**

### CODE REVIEW

**Comment by leoliu** [comment]
This project doesn't compile in OTP 19 getting errors:
```
src/wrangler_refacs.erl:286: syntax error before: '/'
src/wrangler_refacs.erl:293: syntax error before: '/'
src/wrangler_refacs.erl:325: syntax error before: '/'
src/wrangler_refacs.erl:331: syntax error before: '/'
src/wrangler_refacs.erl:337: syntax error before: '/'
src/wrangler_refacs.erl:344: syntax error before: '/'
make: *** [ebin/wrangler_refacs.beam] Error 1
```

**Comment by leoliu** [comment]
ping?

**Comment by simonjohnthompson** [comment]
Sorry, confused here, but is the error in the place that you changed?

Simon


> On 11 May 2016, at 17:48, Leo Liu <notifications@github.com> wrote:
> 
> ping?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/RefactoringTools/wrangler/pull/77#issuecomment-218519267>

Simon Thompson | Professor of Logic and Computation 
School of Computing | University of Kent | Canterbury, CT2 7NF, UK
s.j.thompson@kent.ac.uk <mailto:s.j.thompson@kent.ac.uk> | M +44 7986 085754 | W www.cs.kent.ac.uk/~sjt <http://www.cs.kent.ac.uk/~sjt>

**Comment by huiqing** [comment]
Thanks!

**Comment by leoliu** [comment]
Hi @simonjohnthompson,

The error is not introduced by the changes to -spec's but OTP 19's support for types in more places, for example, https://github.com/erlang/otp/pull/1044. Sorry for this confusion.

Hi @huiqing, thanks for merging it.

**Comment by simonjohnthompson** [comment]
Thanks, and apologies from me for at confusion here

S.

**Comment by leoliu** [comment]
for the record
```
OTP-11879    Application(s): stdlib

               Undocumented syntax for function specifications, -spec
               F/A :: Domain -> Range, has been removed (without
               deprecation).

               Using the is_subtype(V, T) syntax for constraints (in
               function specifications) is no longer documented, and
               the newer syntax V :: T should be used instead. The
               Erlang Parser still recognizes the is_subtype syntax,
               and will continue to do so for some time.
```

**Comment by simonjohnthompson** [comment]
Thanks!

Simon


> On 13 May 2016, at 06:51, Leo Liu <notifications@github.com> wrote:
> 
> for the record
> 
> OTP-11879    Application(s): stdlib
> 
>                Undocumented syntax for function specifications, -spec
>                F/A :: Domain -> Range, has been removed (without
>                deprecation).
> 
>                Using the is_subtype(V, T) syntax for constraints (in
>                function specifications) is no longer documented, and
>                the newer syntax V :: T should be used instead. The
>                Erlang Parser still recognizes the is_subtype syntax,
>                and will continue to do so for some time.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/RefactoringTools/wrangler/pull/77#issuecomment-218957779>

Simon Thompson | Professor of Logic and Computation 
School of Computing | University of Kent | Canterbury, CT2 7NF, UK
s.j.thompson@kent.ac.uk <mailto:s.j.thompson@kent.ac.uk> | M +44 7986 085754 | W www.cs.kent.ac.uk/~sjt <http://www.cs.kent.ac.uk/~sjt>

**Pull request merged**
