### PR TITLE
rebar3 support

### PR DESCRIPTION
**Pull request by fenollp**
This adds support for building with rebar3 (see rebar3.org).

* Why was an (2?) implementation(s) of suffix trees in C chosen instead of a purely Erlang one?

* How do I run tests? I see no test or check target in the generated Makefile nor anything in the README

~~This is a WIP as I am not instructing rebar3 to build the c_src suffix tree(s) yet.~~ done

### CODE REVIEW

**Comment by simonjohnthompson** [comment]
> On 9 Aug 2018, at 12:34, Pierre Fenoll <notifications@github.com> wrote:
> 
> This adds support for building with rebar3 (see rebar3.org <http://rebar3.org/>).
> 
> 
Thanks!

> Why was an (2?) implementation(s) of suffix trees in C chosen instead of a purely Erlang one?
> 
> 
Efficiency: this proved to be much faster than the original Erlang implementation.
> How do I run tests? I see no test or check target in the generated Makefile nor anything in the README
> 
> 

Simon Thompson | Professor of Logic and Computation 
School of Computing | University of Kent | Canterbury, CT2 7NF, UK
s.j.thompson@kent.ac.uk <mailto:s.j.thompson@kent.ac.uk> | M +44 7986 085754 | W www.cs.kent.ac.uk/~sjt <http://www.cs.kent.ac.uk/~sjt>

**Comment by fenollp** [comment]
So how do I run the tests?

**Comment by fenollp** [comment]
Rebar3 support seems complete. How do I run the test suite though?

**Comment by huiqing** [comment]
Thanks! I wrote some test code in the qc_test module a few years ago, but it requires QuickCheck to run it.

**Pull request merged**
